version: '3.3'

services:
  middleware:
    build:
      context: ./middleware
    container_name: middleware
    network_mode: "host"
    ports:
      - "3002:3002" # Expose middleware service on port 3002
    depends_on:
      - pyroscope-client
      - process-exporter

  pyroscope-server:
    build:
      context: ./pyroscope
    container_name: pyroscope-server
    network_mode: "host"
    environment:
      - ROLE=server
    ports:
      - "4040:4040"
    volumes:
      - ./pyroscope-data:/host/pyroscope-data # Mount host filesystem for storage
    privileged: true # Required for eBPF and accessing host resources

  pyroscope-client:
    build:
      context: ./pyroscope
    container_name: pyroscope-client
    network_mode: "host" # Allows access to the host network
    environment:
      - ROLE=client
      - PYROSCOPE_SERVER_ADDRESS=http://0.0.0.0:4040 # Pyroscope server running on the host
    privileged: true 
    pid: "host"

  process-exporter:
    build:
      context: ./process-exporter
    container_name: process-exporter
    privileged: true
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc
      - ./process-exporter:/config